import Head from "next/head";

import LookForShipment from "@/components/LookForShipment";
import ShipmentRequestNotification from "@/components/notifications/ShipmentRequestNotification";
import RequestPickup from "@/components/RequestPickup";
import CreateAccount from "@/components/CreateAccount";

import { getSession, withPageAuthRequired } from "@auth0/nextjs-auth0";

interface Props {
  idToken: string | undefined;
  user:
    | string
    | {
        account_type: string;
      };
}

export default function Home({ idToken, user }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user ? (
        <div id="app">
          <a href="api/auth/logout">Log out</a>
          <RequestPickup />
          <LookForShipment />
          <ShipmentRequestNotification
            requestFrom="Requester"
            pickup="Detroit"
            destination="Chicago"
            shipmentDescription="Description of load and special features requested"
          />
        </div>
      ) : (
        <CreateAccount authId={idToken} />
      )}
    </>
  );
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps({ req, res }) {
    const data = await getSession(req, res);
    const idToken: string | undefined = data?.idToken;

    const response = await fetch(
      `http://127.0.0.1:80/api/v1/getUser/${idToken}`
    );
    const { user } = await response.json();

    return {
      props: { idToken, user },
    };
  },
});
